// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuseumExhibits.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MuseumExhibits.Infrastructure.Migrations
{
    [DbContext(typeof(MuseumExhibitsDbContext))]
    [Migration("20250130212028_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MuseumExhibits.Core.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("MuseumExhibits.Core.Models.Exhibit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArchivalMaterials")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArrivalMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssociatedPersonsAndEvents")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorOrManufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bibliography")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ConfirmationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscoveryTimeAndPlace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ElementCount")
                        .HasColumnType("integer");

                    b.Property<string>("EnteredBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExistenceTimeAndPlace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InventoryVerificationData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsTransportable")
                        .HasColumnType("boolean");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Measurements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MovementDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MuseumDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfCreation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreciousMetalContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreciousStoneContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreservationState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelatedDocuments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RemovalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RemovalReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsibleKeeper")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RestorationDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RestorationRecommendations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReturnDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReturnDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceOfArrival")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Technique")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemporaryStoragePurpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Exhibit");
                });

            modelBuilder.Entity("MuseumExhibits.Core.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExhibitId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsTitleImage")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExhibitId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("MuseumExhibits.Core.Models.Exhibit", b =>
                {
                    b.HasOne("MuseumExhibits.Core.Models.Category", "Category")
                        .WithMany("Exhibits")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MuseumExhibits.Core.Models.Image", b =>
                {
                    b.HasOne("MuseumExhibits.Core.Models.Exhibit", "Exhibit")
                        .WithMany("Images")
                        .HasForeignKey("ExhibitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exhibit");
                });

            modelBuilder.Entity("MuseumExhibits.Core.Models.Category", b =>
                {
                    b.Navigation("Exhibits");
                });

            modelBuilder.Entity("MuseumExhibits.Core.Models.Exhibit", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
